'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------



Partial Public Class [Default]

    ''' <summary>
    ''' form2 control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected form2 As Global.System.Web.UI.HtmlControls.HtmlForm

    ''' <summary>
    ''' ProgressControl control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected ProgressControl As Global.DevExpress.ExpressApp.Web.Controls.ASPxProgressControl

    ''' <summary>
    ''' Content control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected Content As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
