'------------------------------------------------------------------------------
'<auto-generated>
' Generated by the DevExpress.Blazor package.
' To prevent this operation, add the DxExtendStartupHost property to the project and set this property to False.
'
' RuntimeDbChooser.Blazor.Server.csproj:
'
' <Project Sdk="Microsoft.NET.Sdk.Web">
'  <PropertyGroup>
'    <TargetFramework>netcoreapp3.1</TargetFramework>
'    <DxExtendStartupHost>False</DxExtendStartupHost>
'  </PropertyGroup>
'</auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports Microsoft.Extensions.DependencyInjection
Imports Microsoft.AspNetCore.Hosting

<Assembly:HostingStartup(GetType(RuntimeDbChooser.Blazor.Server.DevExpressHostingStartup))>
Namespace RuntimeDbChooser.Blazor.Server

    Public Partial Class DevExpressHostingStartup
        Inherits IHostingStartup

        Private Sub Configure(ByVal builder As IWebHostBuilder)
            builder.ConfigureServices(Function(serviceCollection)
                serviceCollection.AddDevExpressBlazor()
            End Function)
        End Sub
    End Class
End Namespace
